version: '3.8'

services:
  php-pbr:
    build: ./docker/apache
    container_name: apache-dowdow
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - ./:/var/www/html